---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          lfs: true

      - name: "Install and build"
        run: |
          yarn run reinstall
          yarn run build
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: packages/automatic-releases/dist/

